TP-26790 Python 3 upgrade: django-pg-extensions upgrade
Scurri/django-pg-extensions pull request #2
Opened 2022-05-11 14:45 UTC by michalplichta-sc

Python 3 upgrade: django-pg-extensions upgrade
https://scurri.tpondemand.com/entity/26790-python-3-upgrade-django-pg-extensions

As a Scurri developer, I would like to upgrade the django-pg-extensions library to support Python 2.7 and Python 3.4+.

The library can be found here:
https://github.com/Scurri/django-pg-extensions

Tests using `tox` must be implemented to ensure that the upgraded library is supported by both, Python 2.7 and 3.4+.

We must also bump the version so we can later update Scurri requirements.

**Acceptance Criteria**

* The library is upgraded
* Proper tests are implemented
* The version is bumped

**Goal**
Make the library Python 2 and 3 compatible

**Checks**
 - [ ] Acceptance Criteria Satisfied
 - [ ] Code changes are covered by test suite
 - [ ] Pull request is properly formatted

2022-05-12 09:19 UTC, brian-barba-hernandez requested changes

2022-05-12 09:19 UTC, brian-barba-hernandez commented on djangopg/copy.py
> +        if six.PY2:
Join these 2 ifs together, please

2022-05-12 09:19 UTC, brian-barba-hernandez commented on djangopg/fields.py
>          if isinstance(value, str):
This line may refer to binary type, on Python 3:
```
>>> value = str('123')
>>> if isinstance(value, str):
...     value.decode('UTF-8')
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
AttributeError: 'str' object has no attribute 'decode'
```
Please, make sure the coverage of this library is 100%, this library is critical.

2022-05-17 16:11 UTC, michalplichta-sc commented
### Coverage report for Python 3.4
```
Name                                       Stmts   Miss  Cover   Missing
------------------------------------------------------------------------
djangopg/__init__.py                           0      0   100%
djangopg/copy.py                              56     10    82%   27, 51-61
djangopg/fields.py                            46      4    91%   38-45
djangopg/models.py                             0      0   100%
djangopg/postgresql_psycopg2/__init__.py       2      2     0%   3-5
djangopg/postgresql_psycopg2/base.py          13     13     0%   3-27
djangopg/test_settings.py                      5      0   100%
djangopg/where.py                              9      0   100%
------------------------------------------------------------------------
TOTAL                                        131     29    78%
```

2022-05-17 16:24 UTC, brian-barba-hernandez requested changes
Also, as I suggested in slack, please, don't add separated comments for the coverage, add then in the PR description at the top, easier to spot it.

2022-05-17 16:24 UTC, brian-barba-hernandez commented on djangopg/copy.py
> +    columns = list(map(conn.ops.quote_name, columns))
Please cover this change with tests for the `_send_csv_to_postgres` method.

2022-05-18 11:57 UTC, brian-barba-hernandez approved these changes

2022-05-24 15:45 UTC, dmitrynedbaylo-sc requested changes
Please read chat https://scurri.slack.com/archives/C02K3BV0266/p1653404899794079

2022-07-27 09:08 UTC, brian-barba-hernandez commented
Closing as I'll be creating a new PR which will be cleaner

2022-07-27 09:08 UTC, closed without merging